//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CricketSystemEntities : DbContext
    {
        public CricketSystemEntities()
            : base("name=CricketSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hired_table> hired_table { get; set; }
        public virtual DbSet<login_history_table> login_history_table { get; set; }
        public virtual DbSet<order_table> order_table { get; set; }
        public virtual DbSet<product_table> product_table { get; set; }
        public virtual DbSet<user_table> user_table { get; set; }
        public virtual DbSet<payment_table> payment_table { get; set; }
        public virtual DbSet<pawn_product_table> pawn_product_table { get; set; }
        public virtual DbSet<pawn_table> pawn_table { get; set; }
    }
}
