//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pawn_table
    {
        public int Pawn_id { get; set; }
        public int Pawn_Product_id { get; set; }
        public int User_id { get; set; }
        public int Quantity { get; set; }
        public string Condition { get; set; }
        public decimal LoanAmount { get; set; }
        public decimal AmountDue { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string collectionDate { get; set; }
        public string Status { get; set; }
    }
}
