//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pawn_product_table
    {
        public int Pawn_Product_id { get; set; }
        public string Product_type { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public string Image_url { get; set; }
    }
}
