//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_table
    {
        public int Payment_id { get; set; }
        public int Purchase_id { get; set; }
        public string Purchase_Type { get; set; }
        public int User_id { get; set; }
        public string Bank { get; set; }
        public string Card_holder { get; set; }
        public string Card_number { get; set; }
        public string Cvv { get; set; }
        public int ExpMM { get; set; }
        public int ExpYY { get; set; }
        public decimal totatAmount { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Status { get; set; }
    }
}
