//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_table
    {
        public int Product_id { get; set; }
        public int User_id { get; set; }
        public int ProductNo { get; set; }
        public string product_purpose { get; set; }
        public string Product_type { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Image_url { get; set; }
        public string Username { get; set; }
        public string UserType { get; set; }
    }
}
