//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_table
    {
        public int User_id { get; set; }
        public string User_type { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string IDNumber { get; set; }
        public string Gender { get; set; }
        public string Cellno { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime Date_created { get; set; }
        public string Status { get; set; }
    }
}
